name: Build Dreambox

on: workflow_dispatch

jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: ./publish-linux-x64.sh
        working-directory: ./src
      - uses: actions/upload-artifact@v4
        with:
          name: dreambox-linux-x64
          path: ./src/publish/dreambox-linux-x64.tar.gz
