name: Publish Dreambox (Itch.IO)

on:
  workflow_dispatch:
    inputs:
      api-key:
        description: 'API key for uploading to Itch.IO via Butler'
        required: true
        default: ''
      version:
        description: 'Version number'
        required: true
        default: ''

jobs:
  publish_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
          submodules: 'recursive'
      - run: git lfs checkout
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: ./publish-linux-x64.sh
        working-directory: ./src
      - run: echo "::add-mask::$BUTLER_API_KEY"
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_API_KEY: ${{ github.event.inputs.api-key }}
          CHANNEL: linux-x64
          ITCH_GAME: dreambox
          ITCH_USER: crit-chance-studios
          PACKAGE: ./src/publish/dreambox-linux-x64/
          VERSION: ${{ github.event.inputs.version }}
  publish_win_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
          submodules: 'recursive'  
      - run: git lfs checkout
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: ./publish-win-x64.bat
        working-directory: ./src
      - run: echo "::add-mask::$BUTLER_API_KEY"
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_API_KEY: ${{ github.event.inputs.api-key }}
          CHANNEL: windows-x64
          ITCH_GAME: dreambox
          ITCH_USER: crit-chance-studios
          PACKAGE: ./src/publish/dreambox-win-x64/
          VERSION: ${{ github.event.inputs.version }}
